### PR TITLE
roles/checkup/tasks/main.yml: small fixes

### PR DESCRIPTION
**Pull request by zmedico**
* add missing quotes
* use sudo: false for local_action
* fix indentation

@fghaas

### CODE REVIEW

**Comment by fghaas** [comment]
Thanks @zmedico, and apologies — I had missed my last local rebase before pushing this up. I'd already fixed the indentation and quotes bit, but of course that doesn't help you much if I miss the final `git push`.

I'm also happy to implement your suggestion of running the local actions as non-root, but as of Ansible 1.9 [the `sudo` option is deprecated](http://docs.ansible.com/ansible/become.html), so I've put together a patch that uses `become` instead. Really sorry about the hassle, but can I bother you to refetch from upstream and do a hard reset on upstream master?

**Comment by fghaas** [comment]
Unprivileged local actions implemented in 141e8411f2a9aefc978048310a6dad1e63fc9889.

**Comment by zmedico** [comment]
> Really sorry about the hassle, but can I bother you to refetch from upstream and do a hard reset on upstream master?

No problem, it works for me now. Thank you!

**Comment by fghaas** [comment]
@zmedico All right, thanks!

**Pull request closed without merging**
